### ISSUE TITLE
Please add instructions

### ISSUE THREAD

**Issue by tullis** [RedbeeBV/check_mk-eximqueue#1]
Hello,

Thanks for your work on this plugin, I think I'd like to install it.
Please could you add some instructions, or tell me where I could find out more about how to use it?

Many thanks again.

**Comment by Prophecy67** [comment]
Hi Ben, Sure thing. I'll make a manual of how to install it asap, sorry for a little delay!

**Comment by Prophecy67** [comment]
@tullis I updated the manual page on your request
https://github.com/RedbeeBV/check_mk-eximqueue/blob/master/README.md
